// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class NavegacionTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void navegacion() {
    driver.get("http://localhost:4200/");
    driver.manage().window().setSize(new Dimension(1547, 814));
    assertThat(driver.findElement(By.cssSelector(".highlight-card > span")).getText(), is("Hola mundo app is running!"));
    driver.findElement(By.linkText("demos")).click();
    assertThat(driver.findElement(By.cssSelector("app-card:nth-child(2) .card-header")).getText(), is("Cabecera de la tarjeta"));
    driver.findElement(By.linkText("calculadora")).click();
    driver.findElement(By.linkText("contactos")).click();
    assertThat(driver.getTitle(), is("Curso de Angular"));
    assertThat(driver.getTitle(), is("Curso de Angular"));
    driver.findElement(By.cssSelector(".offcanvas-body")).click();
    driver.findElement(By.name("usr")).sendKeys("emp@example.com");
    driver.findElement(By.cssSelector(".fa-sign-in-alt")).click();
    driver.findElement(By.cssSelector(".fa-sign-out-alt")).click();
    driver.findElement(By.name("usr")).click();
  }
}
